# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DtAdded', models.DateTimeField(verbose_name='Date Added')),
                ('Title', models.CharField(max_length=5)),
                ('FirstName', models.CharField(max_length=25)),
                ('LastName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InterestName', models.CharField(max_length=15)),
                ('InterestCode', models.CharField(max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='Interests',
            field=models.ManyToManyField(to='ContactsApp.Interest'),
        ),
    ]
