# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ContactsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RelationshipName', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='Relationship',
            field=models.OneToOneField(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='ContactsApp.Relationship'),
            preserve_default=False,
        ),
    ]
