# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactsApp', '0002_auto_20161210_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='DtAdded',
            field=models.DateField(verbose_name='Date Added'),
        ),
    ]
