# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='short_name',
            field=models.CharField(max_length=25),
        ),
    ]
